name: Assignment Test workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Build services
        run: docker-compose build

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Start services
        run: docker-compose up --detach

      - name: Wait for services to start
        run: sleep 30  # sleep duration
        
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test
        continue-on-error: true
        
      - name: Archive Mochawesome report
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: ../mochawesome-report

      - name: Stop and remove services containers
        run: docker-compose down
